### ISSUE TITLE
decorative blocks after breaking them leave ghost blocks

### ISSUE THREAD

**Issue by SDUBZ** [elytra/Engination#3]
after breaking the block it would leave a fake block and then placing glass back it would reappear 
![2017-05-23_07 58 50](https://cloud.githubusercontent.com/assets/14084377/26330111/ce20575e-3f8d-11e7-8c3c-c1ec5a57382c.png)
![2017-05-23_07 58 27](https://cloud.githubusercontent.com/assets/14084377/26330116/d1e21d32-3f8d-11e7-8caa-9ccebe19c605.png)
![2017-05-23_07 58 23](https://cloud.githubusercontent.com/assets/14084377/26330117/d44c943a-3f8d-11e7-9d7d-d5a686b347ed.png)

**Comment by falkreon** [comment]
Need more info: Creative? Survival? Does this only happen for the block pictured, or for blocks in different sets? How close to spawn are you? Singleplayer or multiplayer?

**Comment by SDUBZ** [comment]
all of the blocks seem to do it

**Comment by SDUBZ** [comment]
and i was in creative when i tried this

**Comment by SDUBZ** [comment]
in survival you cant even mine the blocks with a iron pickaxe

**Comment by falkreon** [comment]
Are you in singleplayer or multiplayer, and if you're in multiplayer, how close to spawn are you?

**Comment by SDUBZ** [comment]
im in singleplayer testing

**Comment by falkreon** [comment]
I can't get that behavior to happen. It might be other mods, it might be a specific forge version, it might be details about your machine. I have no idea, but I can't fix a bug if I can't repro it.
