### ISSUE TITLE
Presidential blocks cause z-fighting when placed next to each other.

### ISSUE THREAD

**Issue by Bluberry-Kat** [elytra/Engination#5]
![image](https://user-images.githubusercontent.com/20749209/48676630-64b34900-eb37-11e8-9ce1-9d1ba27f232b.png)

**Comment by falkreon** [comment]
Presidential blocks are going to continue to be oppressively obnoxious and hostile to nearby blocks at least until version 46.

**Comment by Bluberry-Kat** [comment]
*just got the joke*
ah, yes, of course. to protect the neighboring blocks. thank you

**Comment by Bluberry-Kat** [comment]
:)
